-- 15th May 2022 (module 7)
-- Create fact tables & load data

--FactTable1
CREATE TABLE Fact_ProductSalesTarget
(
    DimProductID INTEGER CONSTRAINT FK_DimProductID FOREIGN KEY REFERENCES Dim_Product(DimProductID) --Foreign Key
   ,DimTargetDateID NUMBER(9,0) CONSTRAINT FK_DimTargetDateID FOREIGN KEY REFERENCES Dim_Date(DATE_PKEY) --Foreign Key
   ,ProductTargetSalesQuantity INTEGER NOT NULL 
);

--Load data into FactTable1
INSERT INTO Fact_ProductSalesTarget 
(
  DimProductID,DimTargetDateID,ProductTargetSalesQuantity
)
VALUES
(
  -1,-1,-1
);

INSERT INTO Fact_ProductSalesTarget
(
  DimProductID, DimTargetDateID, ProductTargetSalesQuantity
)
SELECT DP.DimProductID, DD.DATE_PKEY, TDP.SalesQuantityTarget/365 --DailyTarget 
FROM Dim_Product AS DP
  INNER JOIN STAGE_TARGETDATAPRODUCT AS TDP 
     ON DP.PRODUCTID = TDP.PRODUCTID 
  INNER JOIN Dim_Date AS DD 
    ON DD.YEAR = TDP.YEAR;
 
SELECT * FROM Fact_ProductSalesTarget;
DELETE FROM Fact_ProductSalesTarget;
SELECT * FROM DIM_PRODUCT;

--FactTable2
CREATE TABLE Fact_SRCSalesTarget
(
  DimStoreID INTEGER CONSTRAINT FK_DimStoreID FOREIGN KEY REFERENCES Dim_Store(DimStoreID) --Foreign Key
 ,DimResellerID INTEGER CONSTRAINT FK_DimResellerID FOREIGN KEY REFERENCES Dim_Reseller(DimResellerID) --Foreign Key
 ,DimChannelID INTEGER CONSTRAINT FK_DimChannelID FOREIGN KEY REFERENCES Dim_Channel(DimChannelID) --Foreign Key
 ,DimTargetDateID NUMBER (9,0) CONSTRAINT FK_DimTargetDateID FOREIGN KEY REFERENCES Dim_Date(DATE_PKEY) --Foreign Key
 ,SalesTargetAmount INTEGER NOT NULL 
);

--Load data into FactTable2
INSERT INTO Fact_SRCSalesTarget 
(
  DimStoreID,DimResellerID,DimChannelID, DimTargetDateID, SalesTargetAmount
)
VALUES
(
  -1,-1,-1, -1, -1
);

INSERT INTO Fact_SRCSalesTarget 
(
  DimStoreID 
 ,DimResellerID
 ,DimChannelID
 ,DimTargetDateID 
 ,SalesTargetAmount  
)

SELECT 
  NVL(DS.DimStoreID, -1)
, NVL(DR.DIMRESELLERID, -1)
, DIMCHANNELID
, DATE_PKEY 
, TargetSalesAmount/365 --DAILY

FROM STAGE_TARGETDATACHANNELRESELLERANDSTORE as TDCRS 
INNER JOIN DIM_DATE AS DD
ON DD.YEAR = TDCRS.YEAR
INNER JOIN DIM_CHANNEL AS DC
ON DC.ChannelName = CASE WHEN TDCRS.ChannelName = 'Online' THEN 'On-line' ELSE TDCRS.ChannelName END 

LEFT OUTER JOIN DIM_STORE AS DS
ON DS.StoreNumber =  
CASE 
WHEN TDCRS.TargetName = 'Store Number 5' THEN 5
WHEN TDCRS.TargetName = 'Store Number 8' THEN 8
WHEN TDCRS.TargetName = 'Store Number 10' THEN 10
WHEN TDCRS.TargetName = 'Store Number 21' THEN 21
WHEN TDCRS.TargetName = 'Store Number 34' THEN 34
WHEN TDCRS.TargetName = 'Store Number 39' THEN 39
ELSE NULL END

LEFT OUTER JOIN DIM_RESELLER AS DR
ON TDCRS.TARGETNAME = DR.RESELLERNAME

SELECT * from STAGE_TARGETDATACHANNELRESELLERANDSTORE

SELECT * FROM Fact_ProductSalesTarget;
DELETE FROM Fact_ProductSalesTarget;
SELECT * FROM DIM_PRODUCT;

--FactTable3
CREATE OR REPLACE TABLE Fact_SalesActual
(
  DimProductID INTEGER CONSTRAINT FK_DimProductID FOREIGN KEY REFERENCES Dim_Product(DimProductID) --Foreign Key
 ,DimStoreID INTEGER CONSTRAINT FK_DimStoreID FOREIGN KEY REFERENCES Dim_Store(DimStoreID) --Foreign Key
 ,DimResellerID INTEGER CONSTRAINT FK_DimResllerID FOREIGN KEY REFERENCES Dim_Reseller(DimResellerID) --Foreign Key
 ,DimCustomerID INTEGER CONSTRAINT FK_DimCustomerID FOREIGN KEY REFERENCES Dim_Customer(DimCustomerID) --Foreign Key
 ,DimChannelID INTEGER CONSTRAINT FK_DimChannelID FOREIGN KEY REFERENCES Dim_Channel(DimChannelID) --Foreign Key
 ,DimSaleDateID NUMBER (9,0) CONSTRAINT FK_DimSaleDateID FOREIGN KEY REFERENCES Dim_Date(DATE_PKEY) --Foreign Key
 ,DimLocationID INTEGER CONSTRAINT FK_LocationID FOREIGN KEY REFERENCES Dim_Location(DimLocationID) --Foreign Key
 ,SourceSalesHeaderID VARCHAR(255) NOT NULL
 ,SourceSalesDetailID VARCHAR(255) NOT NULL
 ,SaleAmount VARCHAR(255) NOT NULL 
 ,SaleQuantity VARCHAR(255) NOT NULL 
 ,SaleUnitPrice VARCHAR(255) NOT NULL
 ,SaleExtendedCost VARCHAR(255) NOT NULL
 ,SaleTotalProfit VARCHAR(255) NOT NULL
);

SELECT * FROM STAGE_SALESHEADER
INSERT INTO FACT_SALESACTUAL
(DIMPRODUCTID,
DIMSTOREID,
DIMRESELLERID,
DIMCUSTOMERID,  
DIMCHANNELID,  
DIMSALEDATEID,
DIMLOCATIONID,
SOURCESALESHEADERID,
SOURCESALESDETAILID,
SALEAMOUNT,
SALEQUANTITY,
SALEUNITPRICE,
SALEEXTENDEDCOST,
SALETOTALPROFIT
)
SELECT 
DP.DIMPRODUCTID,
NVL(DST.DIMSTOREID, -1),
NVL(DR.DIMRESELLERID, -1),
NVL(DC.DIMCUSTOMERID, -1),
DCH.DIMCHANNELID,
DD.DATE_PKEY,
DL.DIMLOCATIONID,
STSH.SALESHEADERID,
SD.SALESDETAILID,
SD.SALESAMOUNT,
SD.SALESQUANTITY,
(SD.SALESAMOUNT/SD.SALESQUANTITY) AS SALEUNITPRICE,
DP.PRODUCTCOST AS SALEEXTENDEDCOST,
((SALEUNITPRICE - SALEEXTENDEDCOST) * SD.SALESQUANTITY) AS SALETOTALPROFIT
FROM STAGE_SALESDETAIL AS SD
INNER JOIN STAGE_SALESHEADER STSH ON STSH.SALESHEADERID = SD.SALESHEADERID
INNER JOIN DIM_PRODUCT DP ON DP.PRODUCTID = SD.PRODUCTID
INNER JOIN Dim_Date DD ON STSH.Date = CONCAT(DD.Month_Num_In_Year, '/', DD.Day_Num_In_Month, '/', SUBSTRING(DD.Year, 3, 2))
LEFT OUTER JOIN DIM_STORE DST ON DST.DIMSTOREID = STSH.STOREID
LEFT OUTER JOIN DIM_RESELLER DR ON DR.RESELLERID = STSH.RESELLERID
LEFT OUTER JOIN DIM_CUSTOMER DC ON DC.CUSTOMERID = STSH.CUSTOMERID
LEFT OUTER JOIN DIM_CHANNEL DCH ON DCH.DIMCHANNELID = STSH.CHANNELID
INNER JOIN DIM_LOCATION DL ON DL.DIMLOCATIONID = DST.DIMLOCATIONID 
                           OR DL.DIMLOCATIONID = DR.DIMLOCATIONID 
                           OR DL.DIMLOCATIONID = DC.DIMLOCATIONID